version: '3.8'

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - ../files/minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - internal
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wishlist-files.rule=Host(`files.prosto-namekni.ru`)"
      - "traefik.http.routers.wishlist-files.entrypoints=websecure"
      - "traefik.http.routers.wishlist-files.tls.certResolver=letsencrypt"
      - "traefik.http.services.wishlist-files.loadbalancer.server.port=9000"
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../files/pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - internal
    restart: unless-stopped

  server:
    container_name: server
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    networks:
      - internal
      - dokploy-network
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wishlist-api.rule=Host(`api.prosto-namekni.ru`)"
      - "traefik.http.routers.wishlist-api.entrypoints=websecure"
      - "traefik.http.routers.wishlist-api.tls.certResolver=letsencrypt"
      - "traefik.http.services.wishlist-api.loadbalancer.server.port=8080"

networks:
  internal:
    driver: bridge
  dokploy-network:
    external: true
